#Detecting Neutralizing Anti-Toxin Antibodies
## Author: Jhansi Leslie 


### Reference: Adapted from [Serum Antitoxin Antibodies Mediate Systemic and Mucosal Protection from Clostridium difficileDisease in Hamsters] (http://iai.asm.org/cgi/pmidlookup?view=long&pmid=9916055)

### Background
Add constant amount of toxin that is known to cause cytopathic effect.  Make dilutions of sera and add it to toxin—if sera contain neutralizing antibodies then you will see protection of cells. The titter will be determined by comparing which dilutions were able to provide protective effect. 

Use Vero cells grown in DMEM with 1% pen/strep and 10% fetal calf serum.  

Samples: Day -2,40 Serum/Fecal Extract from mice 712- 715 
Negative control= Toxin + PBS plates , Toxin + D-2 Serum 
Positive control = Toxin + Techlab Anti-Serum  


###Day 1 
#### Seed 10^5 cells in 0.75mL into a 96-well plate
	+	Will need 10 plates of cells to test all serum samples for A and B 
		*	10 plates = 10 flasks
	+	Allow 3 hours for cells to adhere to the wells 
1. 	Determine the CTU100 (minimum dose of toxin required to induce rounding of 100% of cells) for both toxin A and toxin B
	+	Use 4 times the CTU100
	+	The last well with 100% cell rounding is
		* toxin B = 1 ng/mL ~ 1
		* toxin A =7.8125ng/mL  ~8
	
	```
	4  X CTU100 
	1.	Toxin B  = 4 ng/mL
	2.	Toxin A = 32ng/mL
	```	

3. 	Make the toxin up 2x more concentrated than 4CTU100 because there is another 1:2 dilution when the serum/extract is added to the toxin  
4.	Dilution Plate 1: Sera 
	+	Dilute sera in PBS
	+	Note each row of serum will be used to seed both the toxin A and toxin B wells on the toxin plate 
	+	First dilution will be 1/10
		*	Add 15uL of serum to 135uL PBS in columns 1 and 7, mix 
	+	Further dilutions will be 1:2
		*	Ex: Take 70uL from column 1 and add to 70ul of PBS in column 2
5.	Dilute anti-toxin Ab 1/25 to be added to Dilution plate B
6.	Dilution Plate 2 Toxin 
	+	Dilute the toxin in PBS
7.	Dilute saved toxin 1:10, followed by a 1:100 dilution = 1000ng/mL toxin
8.	Dilute further depending on concentration and volume desired 
	+	Add 30ul of toxin solution to all the wells of the plate you
9.	Toxin + Sera (Plate 2)
	+	Add 30uL of serum  (from plate 1) to 30uL of toxin incubate for 1hr at 37C
		*	This is a further 1:2 dilution 
	+	Incubate 1hr at 37C 

6.	Cell Plates
a.	Add 25uL of toxin + serum solution to cells  (cells will be in 75uL of Media)
i.	Note if you add 2x (ex 8ng/mL) toxin to the first plate then you will end up with 1ng/mL of toxin added to the cells. 
7.	Incubate cells 37C o/n
Day 2 ( Protocol Day 2):
1.	Read plates 
a.	At 24 hrs read plate for cell rounding 
b.	Cytotoxicity inhibition titer is defined as the reciprocal of the highest serum dilution that inhibited >50% cell rounding. 




